services:
    mairie_voreppe_user_security.component.authentication.handler.login_success_handler:
        class:  %mairie_voreppe_user_security.component.authentication.handler.login_success_handler.class%
        arguments:  [@router, @security.context, @session]
        tags:
            - { name: 'monolog.logger', channel: 'security' } 
            
    mairie_voreppe_user_security.component.authentication.handler.logout_success_handler:
        class:  %mairie_voreppe_user_security.component.authentication.handler.logout_success_handler.class%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }