<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * ArretePromulgueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArretePromulgueRepository extends \Doctrine\ORM\EntityRepository
{
}
