<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * ArreteModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArreteModelRepository extends \Doctrine\ORM\EntityRepository
{
}
