<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * CategorieReseauOuvrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieReseauOuvrageRepository extends \Doctrine\ORM\EntityRepository
{
}
