<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * CommunAccordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunAccordRepository extends \Doctrine\ORM\EntityRepository
{
}
