<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * DemandeImpreciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeImpreciseRepository extends \Doctrine\ORM\EntityRepository
{
}
