<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * DispositifSecuriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositifSecuriteRepository extends \Doctrine\ORM\EntityRepository
{
}
