<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * EmplacementReseauOuvrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementReseauOuvrageRepository extends \Doctrine\ORM\EntityRepository
{
}
