<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends EntityRepository
{
	/**
	* Fonction qui permet de récupérer les entreprise n'étant pas un maître d'oeuvre ou celles qui le sont, doivent être habilité à
	* être prestataire de DICT
	*
	*/
	public function getEntreprisePrestataire() 
	{
        /**
        * Récupérer depuis le controller les entreprise n'ayant pas de maitre d'oeuvre et celles qui en on un avec l'autorisation d'apparaitre dans les DICT dont
        */
        $query_builder =  $this->createQueryBuilder("e")
                         			->where('e.prestataireDICT = true');


         return $query_builder;
    }


	public function myFindAllEntreprise() 
	{

		 $query_builder =  $this->createQueryBuilder("e")
                                    ->where('e.prestataireDICT = true');

        $results = $query_builder->getQuery()->getResult();
                         			
         return $results;
    }
}
