<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * InitiativeDeclarantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitiativeDeclarantRepository extends \Doctrine\ORM\EntityRepository
{
}
