<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaireRepository extends EntityRepository
{
    public function myFindByMairie($id_mairie)
    {
        $createQueryBuilder = $this->_em->createQueryBuilder()
                                                    ->select('m')
                                                    ->from('MairieVoreppeDemandeTravauxBundle:Maire', 'm')
                                                    ->join('m.periodes', 'p')
                                                    ->where('p.mairie = :id_mairie')
                                                    ->setParameter('id_mairie', $id_mairie);
        
        $resultat = $createQueryBuilder->getQuery()->getResult();

        return $resultat;
    }
}
