<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * MiseHorsTensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseHorsTensionRepository extends \Doctrine\ORM\EntityRepository
{
}
