<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * NonConcerneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NonConcerneRepository extends \Doctrine\ORM\EntityRepository
{
}
