<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends EntityRepository
{
     public function myFindByExploitant($id_exploitant)
    {
        $createQueryBuilder = $this->_em->createQueryBuilder()
                                                    ->select('p')
                                                    ->from('MairieVoreppeDemandeTravauxBundle:Periode', 'p')
                                                    ->where('p.exploitant = :id_exploitant')
                                                    ->setParameter('id_exploitant', $id_exploitant);
        
        $resultat = $createQueryBuilder->getQuery()->getResult();

        return $resultat;
    }
}
