<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends EntityRepository
{
     public function myFindByMairie($id_mairie)
    {
        $createQueryBuilder = $this->_em->createQueryBuilder()
                                                    ->select('p')
                                                    ->from('MairieVoreppeDemandeTravauxBundle:Periode', 'p')
                                                    ->where('p.mairie = :id_mairie')
                                                    ->setParameter('id_mairie', $id_mairie);
        
        $resultat = $createQueryBuilder->getQuery()->getResult();

        return $resultat;
    }
}
