<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * RecepisseDTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepisseDTRepository extends \Doctrine\ORM\EntityRepository
{
}
