<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * RecepisseDICTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepisseDICTRepository extends \Doctrine\ORM\EntityRepository
{
}
