<?php

namespace MairieVoreppe\DemandeTravauxBundle\Entity;

/**
 * TypeRendezVousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRendezVousRepository extends \Doctrine\ORM\EntityRepository
{
}
