services:
    mairievoreppeadmin.admin.exploitant:
        class: MairieVoreppe\AdminBundle\Admin\ExploitantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Exploitant }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\Exploitant
            - MairieVoreppeAdminBundle:ExploitantAdmin
    mairievoreppeadmin.admin.serviceexploitant:
        class: MairieVoreppe\AdminBundle\Admin\ServiceExploitantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Service lié à l'exploitant }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\ServiceExploitant
            - MairieVoreppeAdminBundle:ServiceExploitantAdmin
    mairievoreppeadmin.admin.adresse:
        class: MairieVoreppe\AdminBundle\Admin\AdresseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Adresse }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\Adresse
            - MairieVoreppeAdminBundle:AdresseAdmin
    mairievoreppeadmin.admin.logo:
        class: MairieVoreppe\AdminBundle\Admin\LogoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Logo }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\Logo
            - MairieVoreppeAdminBundle:LogoAdmin
    mairievoreppeadmin.admin.personne:
        class: MairieVoreppe\AdminBundle\Admin\PersonneAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Personne }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\Personne
            - MairieVoreppeAdminBundle:PersonneAdmin
    mairievoreppeadmin.admin.personnemorale:
        class: MairieVoreppe\AdminBundle\Admin\PersonneMoraleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: PersonneMorale }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\PersonneMorale
            - MairieVoreppeAdminBundle:PersonneMoraleAdmin