services:
    mairievoreppeadmin.admin.exploitant:
        class: MairieVoreppe\AdminBundle\Admin\ExploitantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Exploitant }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\Exploitant
            - MairieVoreppeAdminBundle:ExploitantAdmin
    mairievoreppeadmin.admin.serviceexploitant:
        class: MairieVoreppe\AdminBundle\Admin\ServiceExploitantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Service lié à l'exploitant }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\ServiceExploitant
            - MairieVoreppeAdminBundle:ServiceExploitantAdmin
    mairievoreppeadmin.admin.adresse:
        class: MairieVoreppe\AdminBundle\Admin\AdresseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gestion des exploitants, label: Adresse }
        arguments:
            - ~
            - MairieVoreppe\DemandeTravauxBundle\Entity\Adresse
            - MairieVoreppeAdminBundle:AdresseAdmin