<?php

namespace MairieVoreppe\DemandeTravauxBundle\Model;

/**
 * RecepisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepisseRepository extends \Doctrine\ORM\EntityRepository
{
}
