<?php

namespace MairieVoreppe\DemandeTravauxBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * TravauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravauxRepository extends EntityRepository
{
}
