exploitant:
    path:     /
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:index" }

exploitant_show:
    path:     /{id}/show
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:show" }

exploitant_new:
    path:     /new
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:new" }

exploitant_create:
    path:     /create
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:create" }
    methods:  POST

exploitant_edit:
    path:     /{id}/edit
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:edit" }

exploitant_update:
    path:     /{id}/update
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:update" }
    methods:  [POST, PUT]

exploitant_delete:
    path:     /{id}/delete
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:Exploitant:delete" }
    methods:  [POST, DELETE]
