moapersonnephysique:
    path:     /
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:index" }

moapersonnephysique_show:
    path:     /{id}/show
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:show" }

moapersonnephysique_new:
    path:     /new
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:new" }

moapersonnephysique_create:
    path:     /create
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:create" }
    methods:  POST

moapersonnephysique_edit:
    path:     /{id}/edit
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:edit" }

moapersonnephysique_update:
    path:     /{id}/update
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:update" }
    methods:  [POST, PUT]

moapersonnephysique_delete:
    path:     /{id}/delete
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:MOAPersonnePhysique:delete" }
    methods:  [POST, DELETE]
