responsable_exploitant:
    path:     /
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:index" }

responsable_exploitant_by_exploitant:
    path:     /{id}/by_exploitant
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:indexByMairie" }
    
responsable_exploitant_show:
    path:     /{id}/show
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:show" }

responsable_exploitant_new:
    path:     /{id}/new
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:new" }

responsable_exploitant_create:
    path:     /{id}/create
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:create" }
    methods:  POST

responsable_exploitant_edit:
    path:     /{id}/edit
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:edit" }

responsable_exploitant_update:
    path:     /{id}/update
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:update" }
    methods:  [POST, PUT]

responsable_exploitant_delete:
    path:     /{id}/delete
    defaults: { _controller: "MairieVoreppeDemandeTravauxBundle:ReponsableExploitant:delete" }
    methods:  [POST, DELETE]
