services:
    demandetravaux.twig.instanceof_extension:
        class: MairieVoreppe\DemandeTravauxBundle\Twig\Extension\InstanceOfExtension
        tags:
            - { name: twig.extension }
    demandetravaux.ckeditor:
        class:  MairieVoreppe\DemandeTravauxBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }
    demandetravaux.twig.extension.loader:
        class:        Twig_Extension_StringLoader
        tags:
            - { name: 'twig.extension' }
    demandetravaux.entity.arretemodel:
        class: MairieVoreppe\DemandeTravauxBundle\Entity\ArreteModel
        calls:
            - [setServicePdfGenerator, [ @knp_snappy.pdf ]]
    demandetravaux.form.type.reponse.nonconcernee:
        class: MairieVoreppe\DemandeTravauxBundle\Form\NonConcerneType
        tags:
            - { name: form.type, alias: mairievoreppe_demandetravauxbundle_nonconcerne }
    demandetravaux.form.type.reponse.concerne:
        class: MairieVoreppe\DemandeTravauxBundle\Form\ConcerneType
        tags:
            - { name: form.type, alias: mairievoreppe_demandetravauxbundle_concerne }
    demandetravaux.form.type.reponse.demandeimprecise:
        class: MairieVoreppe\DemandeTravauxBundle\Form\DemandeImpreciseType
        tags:
            - { name: form.type, alias: mairievoreppe_demandetravauxbundle_demandeimprecise }
    demandetravaux.form.type.rendezvous.communaccord:
        class: MairieVoreppe\DemandeTravauxBundle\Form\CommunAccordType
        tags:
            - { name: form.type, alias: mairievoreppe_demandetravauxbundle_communaccord }
    demandetravaux.form.type.rendezvous.initiativedeclarant:
        class: MairieVoreppe\DemandeTravauxBundle\Form\InitiativeDeclarantType
        tags:
            - { name: form.type, alias: mairievoreppe_demandetravauxbundle_initiativedeclarant }