services:
#   mairie_voreppe_user.example:
#        class: MairieVoreppe\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    mairievoreppe_user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mairievoreppe_user_registration }

    mairievoreppe_user.profile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mairievoreppe_user_profile }

    mairievoreppe_user.form.handler.profile:
        class: Application\Sonata\UserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@sonata_user.profile.form", "@request", "@fos_user.user_manager", "@ewz_search.lucene"]
        scope: request
        public: false
        
#    mairievoreppe_user.login_listener:
#        class: MairieVoreppe\UserBundle\Listener\LoginListener
#        arguments: ['@security.context', '@doctrine', '@session']
#        tags:
#            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    